---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fwzlym.
--- DateTime: 2023/8/27 17:56
---
-- 参数列表 : 1. voucherId  2. userId
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]

-- 判断库存
local stockKey = "seckill:stock:" .. voucherId
local orderKey = "seckill:order:" .. voucherId
if(tonumber(redis.call('get', stockKey)) <= 0) then
    return 1 -- 库存不足
end

if(redis.call('sismember', orderKey, userId) == 1) then
    -- 用户已经下单
    return 2
end

-- 扣库存
redis.call('incrby', stockKey, -1)
-- 添加用户
redis.call('sadd', orderKey, userId)
-- 添加消息到stream
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)

return 0